apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: media-database-cluster
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 768Mi
  bootstrap:
    initdb:
      database: media
      owner: media-admin
      secret:
        name: media-database-secret
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: media-database-objectstore
