apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - chart: vpa
      repoURL: https://charts.fairwinds.com/stable
      targetRevision: 4.12.2
      helm:
        releaseName: vpa
        valueFiles:
          - $repo/kubernetes/infrastructure/vpa/meta/values.yaml
    - repoURL: https://github.com/KanarekLife/homelab-v2
      targetRevision: HEAD
      ref: repo
  destination:
    name: in-cluster
    namespace: vpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
