apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komga-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: authentik-clientid
      remoteRef:
        key: a355ce3d-15d5-45ca-8c96-b4480130ed87
    - secretKey: authentik-clientsecret
      remoteRef:
        key: f3eb7d66-1a0a-4f80-920e-b44801310090
