apiVersion: v1
kind: ConfigMap
metadata:
  name: komga-oauth-config
  namespace: media
data:
  application.yaml: |
    spring:
      security:
        oauth2:
          client:
            registration:
              authentik:
                client-id: ${KOMGA_AUTHENTIK_CLIENT_ID}
                client-secret: ${KOMGA_AUTHENTIK_CLIENT_SECRET}
                client-authentication-method: client_secret_basic
                authorization-grant-type: authorization_code
                scope: openid, email, profile
                redirect-uri: "{baseUrl}/login/oauth2/code/authentik"
            provider:
              authentik:
                issuer-uri: https://login.nieradko.com/application/o/komga/
    komga:
      oauth2-account-creation: true
