apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: certmanager-cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: api-token
      remoteRef:
        key: "4421b66b-5f23-446a-ae81-b37900d43b80"
