apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rembg-nieradko-com
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  sources:
    - repoURL: https://github.com/KanarekLife/homelab-v2
      targetRevision: HEAD
      ref: repo
    - repoURL: https://github.com/KanarekLife/homelab-v2
      targetRevision: HEAD
      path: kubernetes/applications/rembg-nieradko-com/manifests
  destination:
    name: in-cluster
    namespace: rembg-nieradko-com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
