kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 196Gi
