apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proton-vpn-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: privatekey-p2p
      remoteRef:
        key: "108e3efa-94a5-4df1-a259-b465011eeff0"
    - secretKey: privatekey-nop2p
      remoteRef:
        key: "7a4374cf-2cb3-4da5-9aac-b4650136d8cf"
