apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pia-vpn-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "6244bdeb-bdb8-44b1-8703-b37900fd7eaf"
    - secretKey: password
      remoteRef:
        key: "1a8277ef-1370-4f59-af74-b37900fd7677"
