apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent:5.1.2
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: run
              mountPath: /run
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Warsaw
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: qb-web-ui
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
        - name: vpn
          image: qmcgaw/gluetun:v3.40.0
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "custom"
            - name: VPN_TYPE
              value: "wireguard"
            - name: DNS_ADDRESS
              value: "1.1.1.1"
            - name: DOT
              value: "off"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
          volumeMounts:
            - mountPath: /gluetun/wireguard/
              name: wgconfig
              readOnly: true
      initContainers:
        - name: generate-wg-config
          image: ghcr.io/kanareklife/pia-wg-config:v1
          args:
            [
              "-r",
              "$(PIA_REGION)",
              "-o",
              "/out/wg0.conf",
              "$(PIA_USERNAME)",
              "$(PIA_PASSWORD)",
            ]
          env:
            - name: PIA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-secret
                  key: username
            - name: PIA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-secret
                  key: password
            - name: PIA_REGION
              value: "nl_amsterdam"
          volumeMounts:
            - mountPath: /out
              name: wgconfig
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: wgconfig
          emptyDir: {}
        - name: run
          emptyDir: {}
