apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: files-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: authentik-clientid
      remoteRef:
        key: 44674d14-6a4b-4d4b-aecf-b37900ff2c88
    - secretKey: authentik-clientsecret
      remoteRef:
        key: aa6eb0f1-89da-4e2b-a7aa-b37900ff38f6
