apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com.
      identityURL: https://identity.bitwarden.com.
      auth:
        secretRef:
          credentials:
            key: token
            namespace: default
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: a8746a2e-ef13-4672-b64a-b364008d8f5a
      projectID: d8c0ae80-e1eb-491e-85c7-b37900c5c45e
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
