apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/KanarekLife/homelab-v2
      targetRevision: HEAD
      path: kubernetes/infrastructure/cloudflare-ddns/manifests
      directory:
        recurse: true
  destination:
    name: in-cluster
    namespace: cloudflare-ddns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
