apiVersion: apps/v1
kind: Deployment
metadata:
  name: suwayomi-backup-server-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suwayomi-backup-server
  template:
    metadata:
      labels:
        app: suwayomi-backup-server
    spec:
      # temporary: prefer to keep off overloaded oug node
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - talos-oug-a0q
      containers:
        - name: suwayomi-backup-server
          image: ghcr.io/suwayomi/suwayomi-server:v2.2.2217
          env:
            - name: TZ
              value: "Europe/Warsaw"
            - name: AUTO_DOWNLOAD_CHAPTERS
              value: "true"
            - name: EXTENSION_REPOS
              value: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
            - name: UPDATE_MANGA_INFO
              value: "true"
            - name: AUTH_MODE
              value: "basic_auth"
            - name: AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: suwayomi-backup-server-auth-secret
                  key: username
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: suwayomi-backup-server-auth-secret
                  key: password
            - name: DATABASE_TYPE
              value: "H2"
            - name: DATABASE_URL
              value: "postgresql://media-database-cluster-rw.media.svc.cluster.local:5432/suwayomi-backup"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: media-database-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: media-database-secret
                  key: password
            - name: WEB_UI_FLAVOR
              value: "WebUI"
            - name: WEB_UI_CHANNEL
              value: "stable"
          volumeMounts:
            - name: files
              mountPath: /home/suwayomi/.local/share/Tachidesk
          ports:
            - containerPort: 4567
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 64m
              memory: 768Mi
            limits:
              cpu: 1000m
              memory: 1536Mi
        - name: vpn
          image: qmcgaw/gluetun:v3.41.1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: proton-vpn-secret
                  key: privatekey-nop2p
            - name: FIREWALL_INPUT_PORTS
              value: "4567"
          readinessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 15 # Gives the VPN 15s to handshake first
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3 # Allows 3 strikes before killing the pod
          livenessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 30 # Gives plenty of time for initial setup
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3 # Allows 3 strikes before killing the pod
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "(ip rule del table 51820; ip -6 rule del table 51820) || true",
                  ]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: suwayomi-backup-server-files-pvc
