apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller
spec:
  selector:
    matchLabels:
      app: image-puller
  template:
    metadata:
      labels:
        app: image-puller
    spec:
      containers:
        - name: image-puller
          image: nginx:latest # Replace with your desired image
          command: ["sh", "-c", "sleep infinity"]
