apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-pg-secret
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "09791c63-f795-4f02-859e-b37900ebec0b"
    - secretKey: password
      remoteRef:
        key: "c02c4816-4ad2-4ad9-b550-b37900ebdebb"
