apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - chart: alloy
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.10.0
      helm:
        releaseName: alloy
        valueFiles:
          - $repo/kubernetes/infrastructure/alloy/meta/values.yaml
    - repoURL: https://github.com/KanarekLife/homelab-v2
      targetRevision: HEAD
      ref: repo
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
