apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dex-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: authentik-clientid
      remoteRef:
        key: ea627cd5-4cad-417f-ac15-b37900f4b7fd
    - secretKey: authentik-clientsecret
      remoteRef:
        key: a897e4c7-e2bd-444b-844f-b37900f4cee7
