kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bazarr-config-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    recurring-job-group.longhorn.io/backup: enabled
    recurring-job.longhorn.io/source: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
